const app=document.querySelector("#app");
let route="alerts", authed=true;
let alerts=[];
const nav=[["alerts","Alerta"],["today","Hoy"],["map","Mapa de geocercas"],["profile","Perfil"]];
function shell(content){
 return `<div class="layout"><aside class="sidebar"><div class="brand">Alerta</div><div class="nav">${nav.map(([r,l])=>`<button class="${route===r?"active":""}" onclick="go('${r}')">${l}</button>`).join("")}</div><div class="userbox"><div class="avatar"></div><div><b>Laura</b><div class="muted">Todo sincronizado</div></div></div></aside><main class="main"><div class="topbar">${nav.find(x=>x[0]===route)?.[1]||"Alerta"}</div><div class="content">${content}</div></main></div>`;
}
function go(r){route=r;render()}
function button(t,fn,primary=true){return `<button class="btn ${primary?"primary":""}" onclick="${fn}">${t}</button>`}
function render(){
 if(!authed){login();return}
 let c= route==="alerts"?alertsPage():route==="today"?todayPage():route==="map"?mapPage():profilePage();
 app.innerHTML=shell(c);
}
function login(){app.innerHTML=`<div class="auth"><div class="authcard"><div class="logo">🐧</div><h1>Inicio Sesión</h1><p class="muted">Ingresa con tu cuenta</p><div class="stack"><div class="field"><label>Email</label><input value="laura@unal.edu.co"></div><div class="field"><label>Contraseña</label><input type="password"></div>${button("Iniciar sesión","authed=true;route='alerts';render()")}<button class="btn" onclick="register()">Crear Cuenta</button><button class="btn" onclick="alert('Puedes restablecer tu contraseña desde el correo asociado.')">Olvidé mi contraseña</button></div></div></div>`}
function register(){app.innerHTML=`<div class="auth"><div class="authcard"><div class="logo">🐧</div><h1>Crear Cuenta</h1><p class="muted">Crea tu cuenta para sincronizar alertas</p><div class="stack"><div class="grid2"><div class="field"><label>Nombre</label><input value="Laura"></div><div class="field"><label>Apellido</label><input value="Gómez"></div></div><div class="field"><label>Email</label><input placeholder="correo@ejemplo.com"></div><div class="field"><label>Contraseña</label><input type="password" placeholder="Mínimo 8 caracteres"></div>${button("Crear cuenta","authed=true;route='alerts';render()")}<button class="btn" onclick="login()">Volver</button></div></div></div>`}
function alertsPage(){return `<div class="row"><div><h1 class="title">Tus alertas</h1><p class="muted">Todo sincronizado</p></div>${button("+ Crear alerta","route='new';render()")}</div>${route==='new'?newAlertPage():(alerts.length?`<div class="stack" style="margin-top:25px">${alerts.map(a=>`<div class="card"><b>${a.task}</b><p class="muted">${a.place} · radio ${a.radio} · ${a.notif}</p></div>`).join("")}</div>`:`<div class="card" style="text-align:center;margin-top:60px"><div style="font-size:45px">◯</div><h2>Aún no tienes alertas</h2><p class="muted">Crea tu primera alerta por ubicación o por tarea.</p>${button("+ Crear primera alerta","route='new';render()")}</div>`)}`.replace(/route==='new'\?newAlertPage\(\):/,"")}
function newAlertPage(){return `<div class="card" style="margin-top:25px"><p class="muted">Nueva alerta · configuración completa</p><h1 class="title">¿Cómo quieres que te avise?</h1><h2 class="section">1. Selecciona el disparador</h2><div class="grid2"><div class="trigger selected"><b>Por ubicación (geocerca)</b><p class="muted">Se activa al llegar o salir de un lugar</p></div><div class="trigger"><b>Por tarea o acción</b><p class="muted">Se activa a una hora fija</p></div></div><h2 class="section">2. Elige la ubicación</h2><div class="field"><label>Buscar lugar</label><input id="place" value="Universidad Nacional de Colombia"></div><div class="map" style="margin-top:12px"><div class="pin"></div></div><h2 class="section">3. ¿Qué tan cerca debe estar?</h2><div id="radios">${["Punto exacto","20m","50m","100m","Personalizado"].map(x=>`<button class="btn" onclick="selectRadio(this)">${x}</button>`).join(" ")}</div><input id="slider" type="range" min="0" max="500" value="50" style="width:100%;margin-top:15px"><div class="row"><span class="muted">Exacto</span><span class="muted">500m</span></div><div class="card" style="margin-top:24px;background:#f8fafb"><h2>Detalles de la tarea</h2><div class="field"><label>Nombre de la tarea</label><input id="task" value="Entregar trabajo"></div><div class="options"><b>Perfil de notificación</b><label><input type="radio" name="n" value="Silencio"> Silencio</label><label><input type="radio" name="n" value="Vibración" checked> Vibración</label><label><input type="radio" name="n" value="Sonido"> Sonido</label></div>${button("Crear alerta","createAlert()")}</div></div>`}
function selectRadio(el){document.querySelectorAll("#radios .btn").forEach(b=>b.classList.remove("primary"));el.classList.add("primary")}
function createAlert(){let n=document.querySelector('input[name="n"]:checked')?.value||"Vibración";alerts.push({place:document.querySelector("#place").value,task:document.querySelector("#task").value,radio:document.querySelector("#slider").value+"m",notif:n});alert("¡Alerta creada!\\nSincronizando con tu celular...");route="alerts";render()}
function todayPage(){let days=[["Lun 24",[]],["Mar 25",["Comprar ingredientes"]],["Mié 26",["Entregar trabajo"]],["Jue 27",[]],["Vie 28",["Ir al gym"]],["Sáb 29",[]],["Dom 30",[]]];return `<div class="row"><div><h1 class="title">Hola, Laura</h1><p class="muted">Semana del 24 al 30 de agosto</p></div>${button("Nueva alerta","route='new';render()")}</div><div class="week" style="margin-top:20px">${days.map(d=>`<div class="day"><b>${d[0]}</b>${d[1].map(t=>`<div class="chip">${t}</div>`).join("")}</div>`).join("")}</div><div class="grid2" style="margin-top:20px"><div class="card"><h3>Próximas alertas</h3><p class="muted">Entregar trabajo — U. Nacional</p><p class="muted">Ir al gym — Casa</p></div><div class="card"><h3>Geocercas activas</h3><div style="font-size:28px;font-weight:700">3 lugares</div><button class="btn" onclick="go('map')">Ver en el mapa →</button></div></div>`}
function mapPage(){return `<div class="row"><div><h1 class="title">Mapa y geocercas</h1><p class="muted">Visualiza y administra tus lugares activos.</p></div>${button("Nueva geocerca","alert('Formulario de nueva geocerca')")}</div><div class="map" style="margin-top:20px"><div class="pin"></div></div><h2 class="section">Geocercas activas</h2>${["U. Nacional|Entregar trabajo · radio 50m","Gimnasio|Ir al gym · radio 50m","Casa|Comprar ingredientes · radio 50m"].map(x=>{let [a,b]=x.split("|");return `<div class="card" style="margin-bottom:10px"><div class="row"><div><b>${a}</b><p class="muted">${b}</p></div><div>${button("Editar","alert('Editar '+decodeURIComponent('"+a+"'))",false)} ${button("Eliminar","this.closest('.card').remove()",false)}</div></div></div>`}).join("")}`}
function profilePage(){return `<div class="row"><h1 class="title">Tu perfil</h1>${button("Historial y estadísticas","alert('Completadas: 18\\nPospuestas: 5\\nTasa de cumplimiento: 78%')")}</div><div class="card" style="margin-top:16px"><div class="row"><div style="display:flex;gap:14px;align-items:center"><div class="avatar"></div><div><h2 style="margin:0">Laura Gómez</h2><p class="muted">laura@unal.edu.co</p></div></div>${button("Editar datos","alert('Edición de datos')")}</div></div><div class="card" style="margin-top:16px"><h2>Accesibilidad</h2><div class="row"><span class="muted">Contraste alto</span><b>Desactivado</b></div><div class="row"><span class="muted">Tamaño de fuente</span><b>Mediano</b></div><br>${button("Guardar cambios","alert('Cambios guardados')")}</div><div class="card" style="margin-top:16px"><h2>Sincronización</h2><b>Todo sincronizado</b><p class="muted">Última actualización hoy, 10:42. Tus cambios están guardados en la nube.</p>${button("Reintentar sincronización","alert('Sincronización completada')",false)}</div>`}
render();
